### ISSUE TITLE
One of Inactive/Active Image Resources are required!!

### ISSUE THREAD

**Issue by stovberpv** [varunest/SparkButton#19]
<com.varunest.sparkbutton.SparkButton
            android:id="@+id/spark_button"
            android:layout_width="40dp"
            android:layout_height="40dp"
            app:sparkbutton_activeImage="@drawable/ic_edit_black_48dp"
            app:sparkbutton_inActiveImage="@drawable/ic_edit_white_48dp"
            app:sparkbutton_iconSize="40dp"
            app:sparkbutton_primaryColor="@color/primary_color"
            app:sparkbutton_secondaryColor="@color/secondary_color" />

![image](https://user-images.githubusercontent.com/13037514/27536406-a6f62046-5a77-11e7-917b-c8968264526d.png)

**Comment by kmno** [comment]
i have same issue!

Exception Details java.lang.IllegalArgumentException: One of Inactive/Active Image Resources are required!!   at com.varunest.sparkbutton.SparkButton.init(SparkButton.java:121)   at com.varunest.sparkbutton.SparkButton.<init>(SparkButton.java:68)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

**Comment by varunest** [comment]
Hey can you let me know the version of SparkButton you are using. I will check it out myself.

**Comment by kmno** [comment]
com.github.varunest:sparkbutton:1.0.5
